apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: YWRtaW4=       # "admin" base64 encoded
  mongodb-root-password: QWRtaW4xIQ==   # "Admin1!" base64 encoded
  